// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.terram;

import com.terram.UserRolesDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect UserRolesDataOnDemand_Roo_Configurable {
    
    declare @type: UserRolesDataOnDemand: @Configurable;
    
}
