// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.terram;

import com.terram.UserRoles;
import com.terram.UserRolesDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect UserRolesDataOnDemand_Roo_DataOnDemand {
    
    declare @type: UserRolesDataOnDemand: @Component;
    
    private Random UserRolesDataOnDemand.rnd = new SecureRandom();
    
    private List<UserRoles> UserRolesDataOnDemand.data;
    
    public UserRoles UserRolesDataOnDemand.getNewTransientUserRoles(int index) {
        UserRoles obj = new UserRoles();
        setAuthority(obj, index);
        setUserId(obj, index);
        setUserRolesId(obj, index);
        return obj;
    }
    
    public void UserRolesDataOnDemand.setAuthority(UserRoles obj, int index) {
        String authority = "authority_" + index;
        obj.setAuthority(authority);
    }
    
    public void UserRolesDataOnDemand.setUserId(UserRoles obj, int index) {
        Integer userId = new Integer(index);
        obj.setUserId(userId);
    }
    
    public void UserRolesDataOnDemand.setUserRolesId(UserRoles obj, int index) {
        Integer userRolesId = new Integer(index);
        obj.setUserRolesId(userRolesId);
    }
    
    public UserRoles UserRolesDataOnDemand.getSpecificUserRoles(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        UserRoles obj = data.get(index);
        Long id = obj.getId();
        return UserRoles.findUserRoles(id);
    }
    
    public UserRoles UserRolesDataOnDemand.getRandomUserRoles() {
        init();
        UserRoles obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return UserRoles.findUserRoles(id);
    }
    
    public boolean UserRolesDataOnDemand.modifyUserRoles(UserRoles obj) {
        return false;
    }
    
    public void UserRolesDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = UserRoles.findUserRolesEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'UserRoles' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<UserRoles>();
        for (int i = 0; i < 10; i++) {
            UserRoles obj = getNewTransientUserRoles(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
