// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.terram;

import com.terram.Calendar;

privileged aspect Calendar_Roo_JavaBean {
    
    public String Calendar.getId() {
        return this.id;
    }
    
    public void Calendar.setId(String id) {
        this.id = id;
    }
    
}
